### ISSUE TITLE
PDF 缩放时会出现闪烁

### ISSUE THREAD

**Issue by wineee** [CryFeiFei/QtPdfTest#1]
您好，我尝试编译了这个程序，当调整pdf缩放（包括拉伸程序窗口使其缩放）时，会出现闪烁问题，似乎是没有使用双缓冲。请教如何解决这个问题

Hello, I tried to compile this program. When adjusting the pdf zoom (including stretching the program window to make it zoom), there will be a flickering problem. It seems that double buffering is not used. I am ask how to solve this problem？

**Comment by CryFeiFei** [comment]
你可以自己去做一个双缓冲去试试，这只是一个Qt的demo

**Comment by wineee** [comment]
> 你可以自己去做一个双缓冲去试试，这只是一个Qt的demo

我尝试过，新时代的萌新已经不会控件级别的双缓冲的，网上怎么找都只有用 QPainter 画画那种类型的双缓冲

**Comment by wineee** [comment]
另外大佬你的网站 http://www.cryfeifei.cn/ 挂了

**Comment by CryFeiFei** [comment]
来信收到，我会尽快回复您
